- .circleci/config.yml
- .circleci/gometalinter.json
**What this PR does / why we need it**: The PR adds files needed to enable CircleCI integration for this repository.
```release-note
NONE
```
> ci: enable circleci for repository

- cloud/digitalocean/actuators/machine/actuator.go
Fix typo.
Fixes #
```release-note
NONE
```
> cloud/digitalocean: fix event name typo in machineActuator

- cloud/digitalocean/actuators/machine/actuator.go
Fix Validation for Machine type.
```release-note
NONE
```
> cloud/digitalocean: fix machine validation

- cloud/digitalocean/actuators/machine/actuator.go
- cloud/digitalocean/actuators/machine/userdata.go
- clusterctl/examples/digitalocean/provider-components.yaml.template
This PR adds bootstrap script for nodes and updates machine actuator to use it.
```release-note
Add bootstrap script for nodes and update machine actuator to use the new script.
```
> cloud/digitalocean,clusterctl: add bootstrap script for nodes

- Makefile
- README.md
- clusterctl/examples/digitalocean/README.md
- clusterctl/examples/digitalocean/generate-yaml.sh
This PR adds documentation for the project.
```release-note
NONE
```
> docs: write documentation for the cluster-api-provider-digitalocean

- cloud/digitalocean/actuators/machine/actuator.go
Currently, we're using Go SSH implementation in `GetKubeConfig` function to download `kubeconfig` file from master to the local machine (who executed `clusterctl`).
That approach was based on the fact that SSH key is mounted to the pod. But, `GetKubeConfig` is executed locally, by `clusterctl`, and therefore, we can't rely on that.
Instead, we're using system SSH (by invoking it as a command) to download `kubeconfig`. The reason for that, instead of modifying our Go SSH implementation is that it's hard to handle SSH keys in that case.
User would have to provide path to the key, or use predefined path. Passing path from `clusterctl` to `machine-controller`/`GetKubeConfig` may be hard (or even impossible), so that's not an option. Even if we do …
> cloud/digitalocean: use system ssh for getkubeconfig

- CONTRIBUTING.md
- Makefile
- README.md
This PR moves and improves the guidelines we had in `README.md` to `CONTRIBUTING.md`, as well as guidelines how releases should be handled.
```release-note
NONE
```
> Add contributing guidelines

- README.md
This PR updated the outdated Project Status section in the README file.
Fixes #113
```release-note
NONE
```
> Update Project Status README section

- Makefile
The verify rule will be used for the verify prowjob. 
```release-note
NONE
```
> Makefile: add verify rule

- README.md
Simple fix to complete code markdown which was previously missing the ending backtick.
**Which issue(s) this PR fixes** 
N/A
N/A
N/A
```release-note
NONE
```
> Add missing backtick required to complete code markdown

- pkg/docker/generic/generic.go
- pkg/docker/ubuntu/ubuntu.go
- pkg/scp/scp.go
- pkg/ssh/ssh.go
Signed-off-by: solidnerd <niclas@mietz.io>
This will resolve a part of #109 and will format the last errors without values.
Partly #109
> Make error handling consistent for the remaining packages

- OWNERS
- OWNERS_ALIASES
As the title says
```release-note
NONE
```
> Using go.k8s.io for pointing to OWNERS docs

- OWNERS_ALIASES
My priorities have shifted and I do not have the capacity to be active here.
Fixes #
```release-note
none
```
> Remove alvaroaleman from owners

- cloudbuild.yaml
Add cloudbuild definition
Fixes #
```release-note
NONE
```
/cc @xmudrii 
/kind cleanup
> add cloudbuild

- Makefile
Update the registry where we will push the images and update some release steps
/hold for review and discussion
Fixes #
```release-note
Update registry to be similar to other capX
```
/assign @prksu @xmudrii
> makefile: update registry location and update release steps

- .gitignore
- Makefile
- scripts/kind-with-registry.sh
- tilt-provider.json
Add an initial definition for Tilt for development
- fixes https://github.com/kubernetes-sigs/cluster-api-provider-digitalocean/issues/149
```release-note
Add Tilt definition
```
/assign @prksu @xmudrii
> Add initial Tilt definition

- hack/ensure-doctl.sh
- scripts/ci-e2e.sh
- test/e2e/suite_test.go
This PR adding scripts for running e2e test inside prow
/cc @xmudrii @cpanato @MorrisLaw 
```release-note
NONE
```
> Prepare e2e-test on prowjob

- Makefile
- config/default/manager_image_patch.yaml
- skaffold.yaml
- tilt-provider.json
Fixing the image names, discovered when we cut the release 0.3.0 that was wrong
Fixes #
```release-note
NONE
```
/cc @xmudrii 
/kind bug
> images: fix images name

- test/e2e/e2e_test.go
- test/e2e/resource_generator.go
- test/e2e/utils.go
Add MachineDeployment e2e test
Fixes #150 
```release-note
Add MachineDeployment e2e test
```
> Add MachineDeployment e2e test

- README.md
- docs/roadmap.md
Update documentation by adding compatibility matrix and project roadmap
/cc @xmudrii @cpanato
```release-note
NONE
```
> Updated docs

- clusterctl-settings.json
- metadata.yaml
- templates/cluster-template.yaml
Fixes #176
```release-note
Clusterctl integration
```
> Add clusterctl settings and metadata

- Makefile
Looks like we don't have the pkg anymore, removing that from the makefile and adding the cloud directory
Fixes #
```release-note
makefile: remove pkg and and cloud directory
```
/assign @prksu @xmudrii
> makefile: remove pkg and and cloud directory

- main.go
Add option to customize the health port endpoint
Fixes #
```release-note
manager: add option to customize the health address
```
> manager: add option to customize the health address

- go.mod
- main.go
add option to watch a namespace and refactor the init flags
Fixes #
```release-note
manager: add watch namespace and refactor the init flags
```
/assign @xmudrii @prksu
> manager: add watch namespace and refactor the init flags

- controllers/suite_test.go
- main.go
Continuing the changes to make similar to other providers, this time change the zap to use klogr
Fixes #
```release-note
manager: replace zap to use klogr
```
> manager: replace zap to use klogr

- main.go
another one :), this adds an option to the user configure the sync period
Fixes #
```release-note
manager: add SyncPeriod option to be configured
```
/assign @xmudrii @prksu @MorrisLaw
> manager: add SyncPeriod option to be configured

- metadata.yaml
Sorry @xmudrii the metadata is correct :(
this reverts the or merge here: https://github.com/kubernetes-sigs/cluster-api-provider-digitalocean/pull/188
Fixes #
```release-note
NONE
```
/assign @xmudrii
> revert https://github.com/kubernetes-sigs/cluster-api-provider-digitalocean/pull/188

- test/e2e/config/digitalocean-ci.yaml
- test/e2e/config/digitalocean-dev.yaml
- test/e2e/e2e_test.go
This PR is following up my last PR https://github.com/kubernetes-sigs/cluster-api-provider-digitalocean/pull/190#pullrequestreview-493798719 about adding MachineDeployment scaling and HA cluster creation e2e test
/cc @xmudrii @cpanato @MorrisLaw 
```release-note
NONE
```
> Add md scaling and HA cluster creation e2e test

- Makefile
- docs/releasing.md
Add release guide doc
/cc @kubernetes-sigs/cluster-api-provider-digitalocean-maintainers 
```release-note
NONE
```
> 📖 Add releasing doc

- test/e2e/clean_resources.go
- test/e2e/conformance_test.go
- test/e2e/e2e_test.go
I saw in the DO account some machines/lb hanging around, this will try to make sure we clean everything
Fixes #
```release-note
add cleanup to make sure there is no leftovers in the DO account
```
> add cleanup to make sure there is no leftovers in the DO account

- hack/log/redact.sh
- scripts/ci-conformance.sh
- scripts/ci-e2e.sh
- test/e2e/common.go
- test/e2e/config/digitalocean-ci.yaml
- test/e2e/conformance_test.go
- test/e2e/e2e_test.go
- test/e2e/suite_test.go
e2e: small code organization and scripts to redacted sensitive information
none
```release-note
NONE
```
> e2e: small code organization and scripts to redacted sensitive information

- docs/getting-started.md
Fixes several doc bugs in the getting started guide.
Fixes #204
```release-note
NONE
```
> Improve getting started guide

- OWNERS_ALIASES
ncdc stepping down from maintainership
Fixes #
```release-note
NONE
```
> [0.4] ncdc stepping down from maintainership

- OWNERS_ALIASES
ncdc stepping down from maintainership
Fixes #
```release-note
NONE
```
> ncdc stepping down from maintainership

- hack/do-janitor/do-janitor.go
- test/e2e/clean_resources.go
- test/e2e/common.go
While exploring the code a bit, noticed some little typos and grammatical nits in the log messages. Updated some of them so that they read a bit better.
```release-note
NONE
```
> Updated some log messages throughout the code so that they read more easily.

- controllers/docluster_controller.go
- controllers/domachine_controller.go
Support the cluster.x-k8s.io/paused annotation and Cluster.Spec.Paused field.
Fixes #https://github.com/kubernetes-sigs/cluster-api-provider-digitalocean/issues/251
```release-note
Support the cluster.x-k8s.io/paused annotation and Cluster.Spec.Paused field.
```
> Support capi paused annotation

- controllers/docluster_controller.go
- controllers/domachine_controller.go
backport of https://github.com/kubernetes-sigs/cluster-api-provider-digitalocean/pull/252
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-digitalocean/issues/251
/assign @timoreimann 
```release-note
Support the cluster.x-k8s.io/paused annotation and Cluster.Spec.Paused field.
```
> [backport] Support capi paused annotation

- main.go
Seem there is some miss before that we cannot changes webhook port through `--webhook-port` flag
/cc @cpanato 
```release-note
Fix webhook port
```
> Fix webhook port

- main.go
backport #256 
/cc @cpanato 
```release-note
Fix webhook port 
```
> [backport] Fix webhook port (#256)

- docs/releasing.md
Ref: https://github.com/kubernetes/k8s.io/issues/1597
> master to main cleanup

- README.md
We missed a checkbox in the compatibility matrix.
see [slack for context](https://kubernetes.slack.com/archives/CTND9FHU2/p1643662132135369?thread_ts=1638524022.013200&cid=CTND9FHU2)
```release-note
NONE
```
> Update the compatibility matrix checkbox for v1.0

- Dockerfile
- Makefile
- scripts/ci-conformance.sh
- scripts/go_install.sh
Signed-off-by: cpanato <ctadeu@gmail.com>
- update go install script
we are getting some errors for the periodic job that says the ginkgo is not installed
Fixes #
```release-note
NONE
```
> update go install script

- test/e2e/data/ccm/digitalocean-cloud-controller-manager.yaml
- update ccm to use release 0.1.39
/kind feature
Fixes #
```release-note
update ccm to use release 0.1.39
```
> update ccm to use release 0.1.39

- Makefile
- Tiltfile
- go.mod
- go.sum
- test/e2e/config/digitalocean-ci.yaml
- test/e2e/config/digitalocean-dev.yaml
- update CAPI dependencies to v1.2.1
/kind feature
Fixes #
```release-note
update CAPI dependencies to v1.2.1
```
> update CAPI dependencies to v1.2.1

- Makefile
- Tiltfile
- go.mod
- go.sum
- hack/install-cert-manager.sh
- test/e2e/config/digitalocean-ci.yaml
- test/e2e/config/digitalocean-dev.yaml
**What this PR does / why we need it**
- update CAPI to 1.2.2
Fixes #
```release-note
update CAPI to 1.2.2
```
> update CAPI to 1.2.2

- Dockerfile
Signed-off-by: cpanato <ctadeu@gmail.com>
- update golang to 1.18.6
/assign @timoreimann @MorrisLaw 
Fixes #
```release-note
update golang to 1.18.6
```
> update golang to 1.18.6

- Dockerfile
- Makefile
- Tiltfile
- go.mod
- go.sum
- test/e2e/config/digitalocean-ci.yaml
- test/e2e/config/digitalocean-dev.yaml
Fixes #
- bump capi to v1.2.3
/kind feature
```release-note
bump capi to v1.2.3
```
> bump capi to v1.2.3

- Makefile
- Tiltfile
- go.mod
- go.sum
- test/e2e/config/digitalocean-ci.yaml
- test/e2e/config/digitalocean-dev.yaml
Signed-off-by: cpanato <ctadeu@gmail.com>
- bump CAPI to v1.2.4
/kind feature
Fixes #
```release-note
bump CAPI to v1.2.4
```
> bump CAPI to v1.2.4

- docs/getting-started.md
**What type of PR is this?**
/kind docs
**What this PR does / why we need it:**
Correction of generating a workload cluster command
**Which issue(s) this PR fixes:**
Fixes #372
**Special notes for your reviewer:**
**Does this PR introduce a user-facing change?**
```
NONE
```
```release-note
NONE
```
> docs: Correction of generating a workload cluster command

- test/e2e/data/ccm/digitalocean-cloud-controller-manager.yaml
Signed-off-by: cpanato <ctadeu@gmail.com>
- update ccm to 0.1.42 release
/kind feature
/assign @MorrisLaw @timoreimann 
Fixes #
```release-note
update ccm to 0.1.42 release
```
> update ccm to 0.1.42 release

- Dockerfile
- Makefile
- Tiltfile
- go.mod
- go.sum
- test/e2e/config/digitalocean-ci.yaml
- test/e2e/config/digitalocean-dev.yaml
- update go to 1.19.7
- update CAPI to v1.3.5
/kind feature
/assign @MorrisLaw @timoreimann 
/hold for all tests
Fixes #
```release-note
- update go to 1.19.7
- update CAPI to v1.3.5
```
> Update GO to v1.19.7 and CAPI to v1.3.5

- .github/workflows/lint.yml
- Dockerfile
- controllers/docluster_controller.go
- controllers/domachine_controller.go
- Updates for lint job and Go for the image
/kind feature
Fixes #
```release-note
Updates for lint job and Go for the image
```
> Updates for lint job and Go for the image

- test/e2e/data/ccm/digitalocean-cloud-controller-manager.yaml
- update do ccm to 0.1.45
Fixes #
```release-note
update do ccm to 0.1.45
```
/hold
> update do ccm to 0.1.45

- OWNERS
To reduce noise for upstream maintainers
/kind cleanup
Fixes #
```release-note
NONE
```
> Remove cluster-api-maintainers from reviewers list

- test/e2e/data/ccm/digitalocean-cloud-controller-manager.yaml
- update ccm to v0.1.49
/assign @gottwald @timoreimann 
Fixes #
```release-note
update ccm to v0.1.49
```
> update ccm to v0.1.49
