kubernetes-sigs/cluster-api-provider-digitalocean

- Gopkg.lock
- cloud/digitalocean/actuators/machine/userdata/ubuntu/testdata/simple-node-userdata-test.golden
- cloud/digitalocean/actuators/machine/userdata/ubuntu/userdata.go
- cloud/digitalocean/actuators/machine/userdata/ubuntu/userdata_test.go
- vendor/github.com/pmezard/go-difflib/LICENSE
- vendor/github.com/pmezard/go-difflib/difflib/difflib.go
* Fixes issue in the Ubuntu userdata template. The template used MachineSpec to get the name of the machine, but the name is located in the ObjectMeta of Machine object.
* Finishes unit tests for Ubuntu userdata generating. The unit tests are based on what we have in `machine-controller` - we're storing a file with complete script in the `testdata` directory and then we generate new userdata and compare against existing file. To better visualize the difference, the `difflib` package is used.
```release-note
NONE
```
> userdata/ubuntu: finish unit tests. fix template issue

- clusterctl/examples/digitalocean/cluster.yaml.template
- clusterctl/examples/digitalocean/generate-yaml.sh
- clusterctl/examples/digitalocean/machines.yaml.template
- clusterctl/examples/digitalocean/provider-components.yaml.template
- cmd/cluster-controller/Makefile
- cmd/machine-controller/Dockerfile
- cmd/machine-controller/Makefile
* Fixes Makefiles and Dockerfiles for `cluster-controller` and `machine-controller`. Targets not needed for quay.io are removed. The Makefile now uses our appropriate `quay.io` repositories instead of default `gcr.io`. Errors when building images are fixed.
* Finish script for generating bootstrap manifests. Earlier we just had a simple script for building `provider-config.yam`l. Now, the script is updated to handle `machines.yaml` and `cluster.yaml` manifests as well. Environment variables can be used along with the script to customize resulting manifests.
* Two new repositories are created in `quay.io/kubermatic` - `quay.io/kubermatic/digitalocean-cluster-controller` and …
> Fix scripts for pushing Docker images. Finish script for generating bootstrap manifests.

- .circleci/config.yml
- Makefile
* Push `digitalocean-cluster-controller` and `digitalocean-machine-controller` images from CI.
```release-note
NONE
```
> ci: push to quay.io from CircleCI

- cloud/digitalocean/actuators/machine/userdata/ubuntu/templates.go
- cloud/digitalocean/actuators/machine/userdata/ubuntu/testdata/simple-master-userdata-test.golden
- cloud/digitalocean/actuators/machine/userdata/ubuntu/userdata.go
- cloud/digitalocean/actuators/machine/userdata/ubuntu/userdata_test.go
- cloud/digitalocean/actuators/machine/userdata/userdata.go
- pkg/util/util.go
* Adds new template for cloud-init script for Master instances. The script uses kubeadm to bootstrap a cluster,
* Updates userdata methods to use correct script when it generates cloud-init for Master or Nodes,
* Updates tests to utilize updated methods and checks correct pre-generated files,
* Add `pkg/util` package, currently with only `IsMachineMaster` function. In future, we'll add global helpers here.
* HA is not possible with this setup,
* It uses WeaveNet for CNI by default. I'm not sure what is our preference, but Weave seems to work okay on DO.
TODO:
* Utilize this methods from Machine Actuator (follow-up is coming).
```release-note
Add cloud-init template script for Master instances. …
```
> userdata: create cloud-init script for bootstrapping Master machines

- cloud/digitalocean/actuators/machine/actuator.go
- cloud/digitalocean/actuators/machine/userdata/ubuntu/userdata.go
- cloud/digitalocean/actuators/machine/userdata/userdata.go
- clusterctl/examples/digitalocean/provider-components.yaml.template
* Make Machine Actuator use new userdata methods to generate the cloud-init scripts for both master and nodes,
* Correctly handle Droplet tags,
* Mount kubeadm binary to the `machine-controller` container,
* Fix clusterctl panic when first master is bootstrapping.
```release-note
NONE
```
> cloud/digitalocean: wire machine actuator and userdata methods

- .circleci/config.yml
Currently, we're trying to push new Docker image on every push to master. This PR reduces this, so we push only when there is a tag change. This allows better control over when we push images.
We need a robot account for this to work.
```release-note
NONE
```
> ci: publish docker images only on tag changes

- cloud/digitalocean/actuators/machine/actuator.go
This PR temporarily disables updating the Machines, as we don't have fully implemented logic, especially for masters. This prevents idempotent updates.
```release-note
Temporarily disable Machine upgrades until logic is fully implemented.
```
> cloud/digitalocean: disable updating machines

- cloud/digitalocean/actuators/machine/actuator.go
Fix instance exists check in the update method.
```release-note
NONE
```
> cloud/digitalocean: fix instance exists check in the update method

- cloud/digitalocean/actuators/machine/actuator.go
- pkg/scp/scp.go
This PR implements the `GetKubeConfig` method, used by the Machine Actuator to fetch the `kubeconfig` from master, once it's provisioned.
A follow-up for manifests update will be created.
```release-note
Implement GetKubeConfig method for the machine actuator.
```
> cloud/digitalocean: implement getkubeconfig method

- clusterctl/examples/digitalocean/generate-yaml.sh
- clusterctl/examples/digitalocean/provider-components.yaml.template
This is a follow-up of #23.
This PR updates the manifests generator script to generate SSH key to be used by the machine controller to bootstrap the cluster.
```release-note
Update manifests generator scripts to generate SSH key for machine controller.
```
> clusterctl: generate ssh key for machine controller in generator script

- cloud/digitalocean/actuators/machine/actuator.go
- clusterctl/examples/digitalocean/machines.yaml.template
- clusterctl/examples/digitalocean/provider-components.yaml.template
- pkg/sshutil/sshutil.go
* Deploys the SSH key used by machine-actuator as well,
* Do not fail if SSH key already exist,
* Enable private networking by default,
* Fix master bootstrap script.
```release-note
Deploy machineActuator SSH key to Droplet. Update master bootstrap script to work with Kubernetes < 1.11.
```
> cloud/digitalocean,clusterctl: update  master bootstrap script, deploy machine actuator ssh key to droplet

- cloud/digitalocean/actuators/machine/actuator.go
- cloud/digitalocean/actuators/machine/userdata.go
- clusterctl/examples/digitalocean/provider-components.yaml.template
This PR adds functions for parsing bootstrap scripts for master instances.
The new parser function appends dynamically generated environment variables (generated from template) to the bootstrap script from providerConfig.
That way, we don't need templating in providerConfig bootstrap script, and users have variables that they can use in their bootstrap scripts as well.
TODO in a follow-up:
* Document available environment variables.
```release-note
Generate from template and append needed environment variables to the master bootstrap script.
```
> cloud/digitalocean: add environment variables template for master bootstrap script

- cloud/digitalocean/actuators/machine/actuator.go
Fixes typo in DropletCreateRequest.
```release-note
NONE
```
> cloud/digitalocean: use correct providerConfig field for private_networking

- Gopkg.lock
- cloud/digitalocean/actuators/machine/actuator.go
- cloud/digitalocean/actuators/machine/instancestatus.go
This PR ports the InstanceStatus feature from upstream cluster-api controllers, so we can implement the machineUpdate method.
```release-note
Implement InstanceStatus to allow status of the creation and updates to be saved as an annotation.
```
> cloud/digitalocean: port instancestatus feature

- cloud/digitalocean/actuators/machine/actuator.go
This PR adds check to the `instanceExists` function to skip Machine if it has the ID annotation, but that Droplet doesn't exist anymore.
Related to #53
```release-note
NONE
```
> cloud/digitalocean: ignore already deleted droplets when deleting machine

- cloud/digitalocean/actuators/machine/actuator.go
- clusterctl/examples/digitalocean/cluster.yaml.template
- clusterctl/examples/digitalocean/machines.yaml.template
- clusterctl/examples/digitalocean/provider-components.yaml.template
This PR changes the ProviderConfig bootstrap scripts to deploy the [Flannel](https://github.com/coreos/flannel#flannel) CNI plugin when deploying the cluster.
Also, the `kubeadm` token TTL is raised to prevent failures if worker takes longer time to provision.
Fixes #34.
```release-note
Deploy Flannel CNI plugin with clusterctl.
```
> clusterctl: deploy Flannel CNI plugin

- Gopkg.lock
- cloud/digitalocean/actuators/machine/actuator.go
This PR implements the `Update` method for nodes, which replaces the old node with a new node. First the old node is deleted, then the new node is created.
Fixes #33.
```release-note
Implement the update method for workers.
```
> cloud/digitalocean: implement node upgrades

- README.md
This PR removes the `node updates` TODO from the README.md file.
> docs: remove node updates TODO from the README.md

- clusterctl/examples/digitalocean/machines.yaml.template
- clusterctl/examples/digitalocean/provider-components.yaml.template
- vendor/sigs.k8s.io/cluster-api/clusterctl/clusterdeployer/clusterclient.go
This PR updates manifests to deploy Kubernetes 1.11.3 instead of 1.9.4 by default.
This is required, so we can deploy [`digitalocean-cloud-controller-manager`](https://github.com/digitalocean/digitalocean-cloud-controller-manager) and [`csi-digitalocean`](https://github.com/digitalocean/csi-digitalocean) as addons. If users want to use older Kubernetes versions, they can opt-out of using addons.
```release-note
Deploy Kubernetes 1.11.3 instead of 1.9.4 by default.
```
> clusterctl: use 1.11.3 by default

- README.md
- clusterctl/examples/digitalocean/addons.yaml.template
- clusterctl/examples/digitalocean/provider-components.yaml.template
This PR updates addons manifest to deploy [DigitalOcean Cloud Controller Manager](https://github.com/digitalocean/digitalocean-cloud-controller-manager) when provisioning clusters.
The two key features of [DigitalOcean Cloud Controller Manager](https://github.com/digitalocean/digitalocean-cloud-controller-manager) are:
* node controller: annotates and controls nodes. When node is removed from the cloud (e.g. Machine object is removed), the node will be removed from Kubernetes as well
* loadbalacner controller: service type LoadBalancer based on [DigitalOcean Load Balancers](https://www.digitalocean.com/products/load-balancer/) is supported
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, …
>  clusterctl: deploy do-ccm as addon

- README.md
This PR adds instructions for upgrading and deleting the cluster to the README.md file, as well as adds the link to the `cluster-api` diagram in clusterctl section.
Fixes #51.
Fixes #50 (by linking to `cluster-api` diagram).
```release-note
NONE
```
>  docs: add machine upgrading and cluster delete instructions

- Gopkg.lock
- Gopkg.toml
- vendor/sigs.k8s.io/cluster-api/clusterctl/clusterdeployer/BUILD.bazel
- vendor/sigs.k8s.io/cluster-api/clusterctl/clusterdeployer/clusterclient/BUILD.bazel
- vendor/sigs.k8s.io/cluster-api/clusterctl/clusterdeployer/clusterclient/clientfactory.go
- vendor/sigs.k8s.io/cluster-api/clusterctl/clusterdeployer/clusterclient/clusterclient.go
- vendor/sigs.k8s.io/cluster-api/clusterctl/clusterdeployer/clusterdeployer.go
- vendor/sigs.k8s.io/cluster-api/clusterctl/cmd/BUILD.bazel
- vendor/sigs.k8s.io/cluster-api/clusterctl/cmd/create_cluster.go
- vendor/sigs.k8s.io/cluster-api/clusterctl/cmd/delete_cluster.go
- vendor/sigs.k8s.io/cluster-api/clusterctl/testdata/delete-cluster-no-args-invalid-flag.golden
- vendor/sigs.k8s.io/cluster-api/pkg/apis/cluster/zz_generated.api.register.go
- vendor/sigs.k8s.io/cluster-api/pkg/openapi/openapi_generated.go
Updates cluster-api to `5b128c0f9a` to fix issues with `clusterctl` not creating clusters as intended.
https://github.com/kubernetes-sigs/cluster-api/pull/500
```release-note
NONE
```
> vendor: update cluster-api to 5b128c0f9a

- clusterctl/examples/digitalocean/provider-components.yaml.template
We have decided not to implement `cluster-controller` and `cluster-actuator`, as we don't have resources to manage with it on DigitalOcean.
In future if decided, it could be extend to mange firewalls, or something similar, but for now, no need to deploy it.
Fixes #31.
```release-note
NONE
```
> clusterctl: do not deploy cluster-controller

- README.md
This PR removes the upcoming features section from README as we implemented most of them.
```release-note
NONE
```
> docs: remove upcoming features section

- cloud/digitalocean/actuators/machine/actuator.go
This PR adds two checks:
* IPs are set to Droplet in the Create function. Currently, we're only checking are tags set, but I had a problem that tags were set, but IPs are not, several times
* GetKubeConfig now checks for array size to prevent panics
This also improves clusterctl stability as machine actuator was prone to crashing.
```release-note
NONE
```
> cloud/digitalocean: improve machine-actuator stability

- Gopkg.lock
- cloud/digitalocean/actuators/machine/actuator.go
- cloud/digitalocean/actuators/machine/userdata.go
- clusterctl/examples/digitalocean/provider-components.yaml.template
- pkg/docker/docker.go
- pkg/docker/generic/generic.go
- pkg/docker/ubuntu/ubuntu.go
- vendor/github.com/Masterminds/semver/.travis.yml
- vendor/github.com/Masterminds/semver/CHANGELOG.md
- vendor/github.com/Masterminds/semver/LICENSE.txt
- vendor/github.com/Masterminds/semver/Makefile
- vendor/github.com/Masterminds/semver/README.md
- vendor/github.com/Masterminds/semver/appveyor.yml
- vendor/github.com/Masterminds/semver/collection.go
- vendor/github.com/Masterminds/semver/constraints.go
- vendor/github.com/Masterminds/semver/doc.go
- vendor/github.com/Masterminds/semver/version.go
Currently, we're always bootstrapping a cluster with the latest Docker version. This is a bad practice, as we maybe shouldn't always use the latest version.
Instead, this PR adds mechanism for finding the best Docker version candidate. The version candidate is exposed in the bootstrap script as `CR_PACKAGE` and `CR_VERSION` environment variables.
The bootstrap scripts are updated to use the environment variables. The bootstrap scripts are tested and they work.
Fixes #44.
```release-note
NONE
```
> *: implement and use functions for handling Docker runtime version

- cloud/digitalocean/actuators/machine/actuator.go
- cloud/digitalocean/actuators/machine/deployer.go
Fix a typo made in #73 and move deployer functions to a new file.
```release-note
NONE
```
> cloud/digitalocean: fix typo and move deployer functions

- Gopkg.lock
- Gopkg.toml
- vendor/sigs.k8s.io/cluster-api/Gopkg.lock
- vendor/sigs.k8s.io/cluster-api/Makefile
- vendor/sigs.k8s.io/cluster-api/README.md
- vendor/sigs.k8s.io/cluster-api/clusterctl/clusterdeployer/clusterclient/clusterclient.go
- vendor/sigs.k8s.io/cluster-api/clusterctl/clusterdeployer/clusterdeployer.go
- vendor/sigs.k8s.io/cluster-api/pkg/controller/cluster/BUILD.bazel
- vendor/sigs.k8s.io/cluster-api/pkg/controller/error/BUILD.bazel
- vendor/sigs.k8s.io/cluster-api/pkg/controller/machine/BUILD.bazel
- vendor/sigs.k8s.io/cluster-api/pkg/controller/machinedeployment/controller.go
- vendor/sigs.k8s.io/cluster-api/pkg/controller/machinedeployment/sync.go
- vendor/sigs.k8s.io/cluster-api/pkg/deployer/clusterapiserver.go
- vendor/sigs.k8s.io/cluster-api/pkg/deployer/clusterapiservertemplate.go
This PR updates cluster-api to commit f302034 in order to pick up changes made in https://github.com/kubernetes-sigs/cluster-api/pull/509 and https://github.com/kubernetes-sigs/cluster-api/pull/514
```release-note
NONE
```
> vendor: update cluster-api to f302034

- README.md
- clusterctl/examples/digitalocean/provider-components.yaml.template
There is an upstream bug which prevents Minikube > 0.28 from working correctly with clusterctl.
@alvaroaleman mentioned that setting `hostNetwork: true` for clusterapi-controllers deployment seems to fix the issue (#78).
This fix is not an elegant solution but should help until upstream issue is not fixed.
Relevant upstream issue: https://github.com/kubernetes-sigs/cluster-api/issues/475
Documentation is updated to recommend Minikube < 0.28.
Partially Addresses #73
```release-note
NONE
```
> clusterctl, docs: use hostNetwork for clusterapi-controllers

- cloud/digitalocean/actuators/machine/auth.go
Fail early if DIGITALOCEAN_ACCESS_TOKEN is not set. This should make debugging config issues much easier in case a user forgets to set it. 
```release-note
fail early if DIGITALOCEAN_ACCESS_TOKEN is not set
```
cc @xmudrii
> fail early if DIGITALOCEAN_ACCESS_TOKEN is not set

- .circleci/config.yml
Fixes CirleCI to use new instead of old Make target for publishing images to Quay.
```release-note
NONE
```
> Use new push Make target in CI

- cmd/cluster-controller/Makefile
- cmd/machine-controller/Makefile
This PR updates Makefile to push images to `0.3.0` and `0.3.0-dev` tags.
```release-note
NONE
```
> Update Makefiles to 0.3.0 and 0.3.0-dev

- OWNERS
- OWNERS_ALIASES
This PR establish initial OWNERS file required for upstreaming Cluster-API provider.
Partially addresses #105 
We need lazy vote on this PR by everyone mentioned in OWNERS.
@kris-nova @andrewsykim @alvaroaleman @nikhita 
```release-note
NONE
```
> Establish OWNERS and OWNERS_ALIASES files

- OWNERS
- OWNERS_ALIASES
As per discussion with @roberthbailey, this PR updates the ownership files to match the state of cluster-api ownership.
Addresses part of #105 
```release-note
NONE
```
/cc @roberthbailey @timothysc
> Update OWNERS to match cluster-api OWNERS state

- README.md
Remove recommendation to use Minikube version < 0.28 because there is known CVE and the `hostNetwork` approach seems to fix the issue for newer Minikube versions.
```release-note
NONE
```
> Remove recommended Minikube version

- OWNERS_ALIASES
I don't have the bandwidth for reviews right now.
/cc @xmudrii 
```release-note
NONE
```
> Remove nikhita as cluster-api-do-maintainer

- OWNERS
- OWNERS_ALIASES
This PR updates the OWNERS file to match Cluster-API and CAPI-AWS OWNERS.
```release-note
NONE
```
> Update OWNERS file to match CAPI OWNERS

- OWNERS
- OWNERS_ALIASES
@andrewsykim doesn't have the capacity to be active here and decided to step down as a maintainer.
```release-note
NONE
```
/assign @andrewsykim
> Remove andrewsykim from owners

- OWNERS_ALIASES
This PR adds @cpanato and @prksu as Cluster-API DO maintainers.
TODO: create a PR to add them to test-infra OWNERS and GitHub teams.
```release-note
NONE
```
/assign @cpanato @prksu
/hold
for lazy consensus until 3/25 EOD
~until https://github.com/kubernetes/org/issues/1725 is not merged~
> Add cpanato and prksu as maintainers

- README.md
- Fixes some grammatical typos.
- Adds a link to `cloud-init`, which points to a cloud config example in their docs.
```release-note
NONE
```
> Fix README typo and link to cloud-init doc

- OWNERS_ALIASES
This PR adds @MorrisLaw as an approver. @MorrisLaw is a software engineer at DigitalOcean and is interested to help us with the project.
TODO: create a PR to add them to test-infra OWNERS and GitHub teams.
```release-note
NONE
```
/assign @MorrisLaw 
/hold
for lazy consensus until 3/27
> Add MorrisLaw as a maintainer

- Makefile
- go.mod
- go.sum
- test/e2e/README.md
- test/e2e/e2e_test.go
- test/e2e/manifests/digitalocean-cloud-controller-manager.yaml
- test/e2e/resource_generator.go
- test/e2e/suite_test.go
- test/e2e/utils.go
This PR add e2e test by creating and deleting a single controlplane and one worker cluster. both controlplane and worker created using machine api. 
So in this PR doesn't cover the machine deployment api maybe we can add machine deployment e2e test in the followup
Fixes #121
```release-note
NONE
```
> Initial e2e-test

- scripts/ci-e2e.sh
This PR adding randoms string to `SSH_KEY_NAME` value and also fix e2e test failure because of missing `kustomize` binary
/cc @xmudrii @cpanato 
```release-note
NONE
```
> Use random ssh-key name for e2e test

- Dockerfile
Use `gcr.io/distroless/static:latest` in Dockerfile, as used by other CAPI providers.
```release-note
NONE
```
> Use gcr.io/distroless/static:latest in Dockerfile

- Dockerfile
Cherry-pick #161 to release-0.3 branch.
```release-note
NONE
```
> [release-0.3] Use gcr.io/distroless/static:latest in Dockerfile

- Makefile
This PR drops buildkit from the Makefile because it might cause the issues we're seeing on Google Cloud/Cloud Build.
```release-note
NONE
```
> Drop buildkit from Makefile

- Makefile
This revert partially the PR #163 that removes the buildkit.
I think we can keep that variable but instead, we disable that for now, however, if any contributor wants to build that locally then they can set that.
Until we figure out why the post-stage fail to build when the buildkit is set.
/cc @xmudrii 
if you think this is not useful just close :)
Fixes #
```release-note
NONE
```
> makefile: revert the buildKit but set to disable by default

- examples/addons.yaml
- examples/generate.sh
… are needed to make generate.sh work.
This PR updates the uri's for two kustomize builds in the generate.sh script. Those uri's no longer work with kustomize > 3.5.5 because of a change in go-getter.
Also added a space in the crd files to have proper yaml formating.
Fixes #
NA
NA
```release-note
NONE
```
> Change repository uri to match format for kustomize >= 3.5.5

- config/manager/manager_image_patch.yaml
This PR to specify default manager image tag to `master` since the staging image is tagged with `master` not `latest` tag
/cc @xmudrii 
```release-note
NONE
```
> Define default image tag to master

- main.go
The others providers add both apis when start the manager, maybe we should do the same as well
Fixes #
```release-note
manager: add both v1alpha2 and alpha3 scheme when start
```
/assign @prksu @xmudrii
> manager: add both v1alpha2 and alpha3 scheme when start

- .golangci.yml
- main.go
continuing the changes to make more similar to the other providers, this adds the profiler port to expose to pprof profiler when needed.
Fixes #
```release-note
manager: add profiler port to expose pprof profiler
```
/assign @prksu @xmudrii @MorrisLaw
> manager: add profiler port to expose pprof profiler

- metadata.yaml
We did not release version 0.4.x yet, we are on 0.3.0, this PR fix the metadata.yaml to point to the correct release that clusterctl can use.
Fixes #
```release-note
NONE
```
/cc @xmudrii
> fix metadata.yaml to use the correct release

- Makefile
makefile: remove unused test-integration
similar from: https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/979
NONE
```release-note
NONE
```
> makefile: remove unused test-integration

- examples/provider-components/manager_tolerations_patch.yaml
Fixes a mismatch on the kustomization patch for provider-components.
This could also be addressed by adjusting [the name on the referenced Deployment](https://github.com/kubernetes-sigs/cluster-api-provider-digitalocean/blob/7405bd11063b51c53ef8d34d8ece4d77f28fba3d/config/manager/manager.yaml#L5). Let me know if you prefer that.
```release-note
NONE
```
> Fix manager tolerations patch for provider-components

- examples/controlplane/controlplane.yaml
- examples/machinedeployment/machinedeployment.yaml
Add the required `clusterName` field to `Machine*`.
I assume that the cluster name used to be covered by [this label](https://github.com/kubernetes-sigs/cluster-api-provider-digitalocean/blob/a0f34699d6a2a14712a6962bcd8f96d03168f8d8/examples/controlplane/controlplane.yaml#L7) in the past. I wasn't 100% sure if that label (and the neighboring `cluster.x-k8s.io/control-plane`) were now obsolete and can/should be deleted.
Please let me know if that's the case and update the PR accordingly.
```release-note
NONE
```
> Add missing clusterName to Machine

- Makefile
- hack/do-janitor/do-janitor.go
- scripts/ci-janitor.sh
- test/e2e/common.go
Add go code to clean up resources in the CAPDO DO Account that is older than 2 days to avoid account limits and spend $ for nothing.
I will add a periodic job in prow to run every day
/kind feature
/assign @MorrisLaw @prksu @xmudrii 
mention @timoreimann as well to be aware :)
Fixes #
```release-note
janitor: add code to clean the DO account for capdo
```
> janitor: add code to clean the DO account for capdo

- cloud/services/computes/droplets.go
- cloud/services/networking/loadbalancers.go
When a digitalocean/godo request fails due to a network error, the returned `response` variable will be nil. Thus, we need to check for nil in case of a non-nil error before referencing `response` fields to avoid panicking.
As a drive-by improvement, we also simplify how we return the droplet variable when no error occurs.
```release-note
Avoid panic on networking errors in get droplet requests
```
> Avoid panic on network error in DO API get requests

- controllers/domachine_controller.go
Do not mark droplet create failures as terminal.
This allows to address transient errors through automatic reconciles.
**Which issue(s) this PR fixes**:
Fixes #214
```release-note
Do not mark droplet create failures as terminal to allow automatic remediation
```
> Do not mark droplet create failures as terminal

- controllers/docluster_controller.go
- controllers/domachine_controller.go
Remove finalizer when cloud resource is found absent.
This is to ensure that reconciles can complete even when cloud resources (droplets, LBs) cannot be referenced anymore.
**Which issue(s) this PR fixes**:
Fixes #218
Fixes #219
```release-note
Remove finalizer when cloud resource is found absent
```
> Remove finalizer when cloud resource is found absent

- examples/digitalocean-cloud-controller-manager.yaml
Currently, our example CCM uses the host IP address for the Kubernetes service host. This is problematic for cases where the original master node disappears (through, say, an initial upscale and subsequent downscale of the control plane) since the certificate won't be valid for that IP address anymore. Example output showing the problem:
```
E1215 23:06:20.726439       1 leaderelection.go:330] error retrieving resource lock kube-system/cloud-controller-manager: Get https://10.116.0.44:6443/api/v1/namespaces/kube-system/endpoints/cloud-controller-manager: x509: certificate is valid for 10.96.0.1, 67.205.137.20, 138.197.227.228, not 10.116.0.44
```
The solution is to not overwrite the Kubernetes service host environment variable and let CCM use the …
> Let CCM reach API server through k8s svc to avoid bad TLS cert

- Makefile
Removes deprecated generate-examples Makefile target (follow-up from #224).
```release-note
NONE
```
> Remove deprecate generate-examples Makefile target

- api/v1alpha3/tags.go
- api/v1alpha3/tags_test.go
- cloud/scope/cluster.go
- cloud/services/computes/droplets.go
- cloud/services/networking/loadbalancers.go
This PR adds Cluster UID in Loadbalancer name and adds an additional tag that contains Cluster UID for droplet target tag to allow creating two or more clusters with the same name but different namespace in the single management cluster.
**Which issue(s) this PR fixes**:
Fixes #217
/cc @timoreimann 
```release-note
Add Cluster UID in Loadbalancer name and Droplet target tag
```
> Add Cluster UID in Loadbalancer name and Droplet target tag

- api/v1alpha3/docluster_types.go
This PR adds `omitempty` json tag to `ControlPlaneDNS` field. It's fine since `ControlPlaneDNS` is optional.
cc @gottwald 
```release-note
NONE
```
> Omitempty ControlPlaneDNS

- api/v1alpha3/docluster_webhook.go
- api/v1alpha3/domachine_webhook.go
- api/v1alpha3/domachinetemplate_webhook.go
- api/v1alpha3/zz_generated.deepcopy.go
- config/certmanager/certificate.yaml
- config/certmanager/kustomization.yaml
- config/certmanager/kustomizeconfig.yaml
- config/crd/kustomization.yaml
- config/crd/kustomizeconfig.yaml
- config/crd/patches/cainjection_in_doclusters.yaml
- config/crd/patches/cainjection_in_domachines.yaml
- config/crd/patches/cainjection_in_domachinetemplates.yaml
- config/crd/patches/webhook_in_doclusters.yaml
- config/crd/patches/webhook_in_domachines.yaml
- config/crd/patches/webhook_in_domachinetemplates.yaml
- config/kustomization.yaml
- config/patch_crd_webhook_namespace.yaml
- config/webhook/kustomization.yaml
- config/webhook/kustomizeconfig.yaml
- config/webhook/manager_webhook_patch.yaml
- config/webhook/manifests.yaml
- config/webhook/service.yaml
- main.go
Add support for adission webhook
Fixes #198
```release-note
Support admission webhook
```
> Add admission webhook

- cloud/services/computes/droplets.go
- cloud/services/computes/images.go
Save on API requests and stop querying for the image ID from the DO API if the numeric ID is already given: a failure to reference the image would show up during the droplet create request and lead to the same backoff that we run into today.
Also refactor the code and improve error messages slightly as a drive-by change.
```release-note
NONE
```
> Minimize API requests by skipping to check a given image ID

- api/v1alpha3/docluster_types.go
- config/crd/bases/infrastructure.cluster.x-k8s.io_doclusters.yaml
- controllers/docluster_controller.go
- main.go
- util/dns/dns.go
- util/dns/dns_test.go
- util/dns/resolver/faker.go
- util/dns/resolver/resolver.go
This PR move DNS propagation helpers to own packages since `cloud` directory is devoted to related cloud provider stuff
/cc @gottwald 
/assign @timoreimann 
```release-note
None
```
> Move dns propagnation helpers to own packages

- cloud/scope/cluster.go
- cloud/scope/machine.go
- controllers/domachine_controller_unit_test.go
- controllers/suite_test.go
- go.mod
- main.go
The klog v1 dependency used is quite old now, and the k/k repo has
switched to more recent v2 versions for quite some time now.
This updates klog usage to use the v2 package version.
This is part of an overall effort along with updating the k-sigs/cluster-api repo here:
https://github.com/kubernetes-sigs/cluster-api/pull/4284
```release-note
NONE
```
> Update klog dependency to v2

- test/e2e/config/digitalocean-ci.yaml
- test/e2e/config/digitalocean-dev.yaml
Using the release CAPI artifacts, the images was not published so that was failing, now it is live and we can use the released artifacts 
/assign @prksu @timoreimann @MorrisLaw 
Fixes #
```release-note
NONE
```
> capi: using released artifacts

- hack/do-janitor/do-janitor.go
**What this PR does / why we need it**: We are currently using the same DO account for running KOPS e2e tests. Please see the prow job status [here](https://prow.k8s.io/?job=e2e-kops-do-calico). and the kops test grid dashboard [here ](https://testgrid.k8s.io/sig-cluster-lifecycle-kops#e2e-kops-do-calico)
Per discussion with @timoreimann we thought of adding a cleanup job just in case some of the old resources weren't cleaned up . Since we saw this code was already generically handling cleaning up droplets and load balancer resources, I am updating this to also cleanup volumes that KOPS uses to store etcd data.
**Special notes for your reviewer**:  Tested this locally, and it seems to work as expected. Please see the logs for reference -
```
go run hack/do-janitor/do-janitor.go
2021/06/15 …
```
> Update janitor job to remove volumes used by kops e2e jobs

- Makefile
- hack/version.sh
- main.go
- version/version.go
noticed that we don't expose a version for the manager, this PR add the version and output that when the manager start
/assign @prksu @timoreimann @MorrisLaw 
/kind feature
will cherry pick that to the release-1.0 branch when merged
Fixes #
```release-note
add version implementation and output when starting the manager
```
> add version implementation and output when starting the manager

- api/v1beta1/docluster_webhook.go
Fixes the validation error message around `controlPlaneEndpoint` that incorrectly showed the content of the region due to a copy-paste mistake.
```release-note
Fix controlPlaneEndpoint validation error message
```
/assign @cpanato @MorrisLaw
> Fix controlPlaneEndpoint validation error message

- api/v1beta1/docluster_webhook.go
Fixes the validation error message around `controlPlaneEndpoint` that incorrectly showed the content of the region due to a copy-paste mistake.
Cherry-pick from #287.
```release-note
Fix controlPlaneEndpoint validation error message
```
/assign @cpanato
> Fix controlPlaneEndpoint validation error message (release-1.0)

- docs/getting-started.md
noticed a link was broken in the `getting-started` guide, this PR points that link to the correct `drivers list` page
```release-note
NONE
```
> update to use the current minikube drivers link

- Dockerfile
- Makefile
- test/e2e/config/digitalocean-ci.yaml
- test/e2e/config/digitalocean-dev.yaml
- test/e2e/data/ccm/digitalocean-cloud-controller-manager.yaml
- test/e2e/data/cni/calico/calico.yaml
- update go to 1.17.7
- update capi to v1.1.1
- update prebuilt images
- update calico
- update ccm
pre-built images
```console
$ doctl compute image list
ID           Name                                               Type        Distribution    Slug    Public    Min Disk
63624555     cluster-api-ubuntu-1804-v1.16.2-1589476338         snapshot    Ubuntu                  false     25
80071030     Cluster API Kubernetes v1.18.16 on Ubuntu 20.04    snapshot    Ubuntu                  false     25
93100171     Cluster API Kubernetes v1.20.10 on Ubuntu 20.04    snapshot    Ubuntu                  false     25
96195649     Cluster API Kubernetes v1.22.4 on Ubuntu 20.04     snapshot    Ubuntu                  false     25
96197681     Cluster API …
```
> Update image / go and capi also calico and ccm

- Dockerfile
- Makefile
- controllers/docluster_controller.go
- controllers/domachine_controller.go
- scripts/kind-with-registry.sh
/kind feature
- fix ldflags when building the image
- update create kind script
- add check for pause annotation
the check for the pause annotation is needed for some clusterctl operations like move/backup
/hold for non required tests
Fixes #
```release-note
add pause annotation check
```
> add pause annotation check

- test/e2e/capi_test.go
- test/e2e/config/digitalocean-ci.yaml
- test/e2e/data/infrastructure-digitalocean/cluster-template-kcp-remediation.yaml
- test/e2e/data/infrastructure-digitalocean/cluster-template-md-remediation.yaml
Signed-off-by: Carlos Panato <ctadeu@gmail.com>
/kind feature
- tests/e2e: add remediation tests
/hold for capi tests
Fixes #
```release-note
tests/e2e: add remediation tests
```
> tests/e2e: add remediation tests

- Makefile
- go.mod
- go.sum
- test/e2e/capi_test.go
- test/e2e/config/digitalocean-ci.yaml
- test/e2e/data/infrastructure-digitalocean/cluster-template-upgrades.yaml
/kind feature
- e2e/tests: add upgrade k8s tests
need test-infra PR to update prow jobs: https://github.com/kubernetes/test-infra/pull/25289
/hold for tests and prow job update
n/a
```release-note
e2e/tests: add upgrade k8s tests
```
> e2e/tests: add upgrade k8s tests

- OWNERS
- OWNERS_ALIASES
- owners: update/sync capi owners
- owners: add missing emeritus members
emeritus was missing in the owners file
cc @xmudrii @andrewsykim @fabriziopandini 
Fixes #
```release-note
NONE
```
> owners: add missing emeritus members and sync capi owners

- api/v1alpha3/types.go
- api/v1alpha3/zz_generated.conversion.go
- api/v1alpha4/types.go
- api/v1alpha4/zz_generated.conversion.go
- api/v1beta1/types.go
- config/crd/bases/infrastructure.cluster.x-k8s.io_doclusters.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_doclustertemplates.yaml
- controllers/docluster_controller.go
DO LB uuid is currently stored in status. Upon restore, we lose this information and capdo creates a new LB instead of re-using the existing LB. This PR adds the lb uuid in the spec. And updates the docluster controller to prefer the spec uuid over status if present. 
Fixes #290 
- I only made this change for v1beta1. And ran `make generate`, got a few warnings like:
```
E1228 13:28:36.045121   30566 conversion.go:755] Warning: could not find nor generate a final Conversion function for sigs.k8s.io/cluster-api-provider-digitalocean/api/v1beta1.DOLoadBalancer …
```
> add lb uuid to docluster spec

- Makefile
- Tiltfile
- go.mod
- go.sum
- test/e2e/config/digitalocean-ci.yaml
- test/e2e/config/digitalocean-dev.yaml
- Update capi 115 and capdo images
Fixes #
```release-note
Update capi 115 and capdo images
```
> Update capi 115 and capdo images

- api/v1beta1/docluster_webhook.go
Fixes #334 
```release-note
Allow updates to control plane endpoint 
```
> allow updating the control plane endpoint if previously set

- templates/cluster-template-ext-etcd-storage.yaml
Preformatted disks in DOBS are formatted by the droplet OS after the disk is attached to the droplet and get automounted afterwards. This is a race condition between the formatting part and the remount that capi does. In error cases you could end up with a crashing formatter that leaves you with a tiny initial FS that is not grown to the specified value.
In order to avoid this, we need to switch to non-preformatted disks and let capi take care of FS creation.
```release-note
NONE
```
> Switch to non-preformatted etcd DOBS volumes

- hack/do-janitor/do-janitor.go
Cleans up ssh keys from our DO test account whenever do-janitor is called.
Fixes #238 
Not 100% sure how this will work since I'm not able to compare a `createdAt` time value to the `timeToCleanInHours` value we'd typically use within do-janitor (godo.Key does not have this as an available field nor does it seem to ever set one implicitly somewhere). It seems like we only run do-janitor when we want to clean up old resources in the DO account. The only problem I can think of is if we want there to be some longstanding ssh keys to exist within the DO account …
> clean up ssh keys when cleaning up e2e test resources

- Dockerfile
- Makefile
- Tiltfile
- go.mod
- go.sum
- test/e2e/config/digitalocean-ci.yaml
- test/e2e/config/digitalocean-dev.yaml
- Bump CAPI to V1.2.6 and Go to 1.18.8
/kind feature
/assign @timoreimann @MorrisLaw 
/hold for non required tests
Fixes #
```release-note
Bump CAPI to V1.2.6 and Go to 1.18.8
```
> Bump CAPI to V1.2.6 and Go to 1.18.8

- OWNERS
- OWNERS_ALIASES
I'm leaving DigitalOcean and moving on to another company. I won't be contributing to this much at all with the new switch so I'm proposing @gottwald to take my place as co-maintainer because he still contributes to the project actively and has a good understanding of the project overall.
```release-note
NONE
```
> Update co-maintainers file to make Ingo Gottwald a co-maintainer and remove myself and add my name to emeritus approvers list

- Makefile
- hack/ensure-kubectl.sh
There are still references to https://storage.googleapis.com/kubernetes-release instead of https://dl.k8s.io/
dl.k8s.io is the correct advertised download host and will eventually move to be fastly shielding a fully community-owned bucket
ref: https://github.com/kubernetes/k8s.io/issues/2396
```
NONE
```
> Fixed: use dl.k8s.io, not kubernetes-release bucket

- scripts/ci-conformance.sh
- scripts/ci-e2e.sh
- not fail the command if is not able to delete the key
we have a janitor job that will clean that eventually so we dont need to fail the job if cannot delete the key
/assign @gottwald @timoreimann 
Related to https://github.com/kubernetes-sigs/cluster-api/issues/8784
```release-note
NONE
```
> not fail the command if is not able to delete the key

- .github/dependabot.yml
- .github/workflows/lint.yml
- .golangci.yml
- Dockerfile
- Makefile
- controllers/docluster_controller.go
- controllers/domachine_controller.go
- scripts/ci-test.sh
- util/dns/resolver/faker.go
- add github actions to run golangci-lint  and update Go to 1.19.12
other providers are using GH action for small jobs, the lint is a quick one and very useful 
/assign @timoreimann @gottwald
Fixes #
```release-note
add github actions to run golangci-lint  and update Go to 1.19.12
```
> add github actions to run golangci-lint  and update Go to 1.19.12

- main.go
This allows customization of the client-side throttling in client-go and sets a higher initial default.
It is necessary for bigger setups with many domachines.
The approach and naming of the flags are taken 1:1 from cluster API to keep things consistent.
Fixes #
```release-note
add "kube-api-qps" and "kube-api-burst" flags to enable customization of the kube client-side throttling" 
```
/assign @timoreimann @cpanato
> Allow customization of client-go throttling

- Makefile
- Tiltfile
- go.mod
- go.sum
- test/e2e/config/digitalocean-ci.yaml
- test/e2e/config/digitalocean-dev.yaml
- update CAPI to 1.4.8
/kind feature cleanup
Fixes #
```release-note
update CAPI to 1.4.8
```
> [release-1.4] update CAPI to 1.4.8

- Makefile
- Tiltfile
- hack/install-cert-manager.sh
- update cert manager to v1.14.4
/assign @timoreimann @gottwald 
Fixes #
```release-note
update cert manager to v1.14.4
```
> update cert manager to v1.14.4

- hack/do-janitor/do-janitor.go
The nested `ListOptions` struct is a pointer that needs to be initialized. Otherwise, the code will crash with a nil pointer exception when incrementing the page. This has been happening for a while: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-provider-digitalocean-janitor/1831360184321052672
```release-note
NONE
```
> janitor: fix listing

- docs/getting-started.md
I was trying out the [getting started guide](https://github.com/kubernetes-sigs/cluster-api-provider-digitalocean/tree/main/docs) and noticed the following:
- The Kubernetes version in the `clusterctl generate cluster` command is outdated. If you try to run this today you'll face issues with kubeadm init. I wasn't able to capture the exact kubeadm error, but upgrading the version fixed the kubeadm errors.
- The release manifest url for digitalocean-cloud-controller-manager was also incorrect. This PR updates this to the latest version as well.
CC: @gottwald @varshavaradarajan 
No docs changes needed here, the changes are only to the getting started guide.
```release-note
NONE …
```
> Updated K8s version and fix url in getting started guide
